### ISSUE TITLE
Unable to see logs on Kibana

### ISSUE THREAD

**Issue by akash-karve-dev** [ebubekirdinc/SuuCat#10]
According to wiki, we can use http://localhost:5601/app/home#/ to view Kibana dashboard. 
It also says we can login using below credentials,
user: elastic
password: changeme

I am unable to find login screen.

**Comment by ebubekirdinc** [comment]
It was like that before.  I'll update the wiki.
This version of Kibana does not need a login. 
I can even access Kibana from a private Chrome tab without logging in.
